// backend/src/config/permissions.js
// Centralized Role-Based Access Control (RBAC) Permission Matrix

export const PERMISSIONS = {
  // Workflow Permissions
  WORKFLOW_CREATE: 'workflow.create',
  WORKFLOW_READ_SELF: 'workflow.read.self',
  WORKFLOW_READ_TEAM: 'workflow.read.team',
  WORKFLOW_READ_DEPARTMENT: 'workflow.read.department',
  WORKFLOW_READ_ALL: 'workflow.read.all',
  WORKFLOW_UPDATE_SELF: 'workflow.update.self',
  WORKFLOW_UPDATE_ASSIGNED: 'workflow.update.assigned',
  WORKFLOW_UPDATE_ALL: 'workflow.update.all',

  // Task Permissions
  TASK_READ_SELF: 'task.read.self',
  TASK_READ_TEAM: 'task.read.team',
  TASK_READ_DEPARTMENT: 'task.read.department',
  TASK_READ_ALL: 'task.read.all',
  TASK_CREATE: 'task.create',
  TASK_ASSIGN: 'task.assign',
  TASK_COMPLETE: 'task.complete',

  // Approval Permissions
  APPROVAL_READ: 'approval.read',
  APPROVAL_APPROVE: 'approval.approve',
  APPROVAL_REJECT: 'approval.reject',

  // Domain Specific Permissions
  EXPENSE_READ: 'expense.read',
  EXPENSE_PROCESS: 'expense.process',
  ONBOARDING_READ: 'onboarding.read',
  ONBOARDING_MANAGE: 'onboarding.manage',
  HELPDESK_READ: 'helpdesk.read',
  HELPDESK_MANAGE: 'helpdesk.manage',

  // Operations & Reporting
  REPORT_READ: 'report.read',
  REPORT_GENERATE: 'report.generate',
  MONITOR_READ: 'monitor.read',
  MONITOR_RUN: 'monitor.run',

  // Integration & Google Permissions
  INTEGRATION_GOOGLE_CONNECT: 'integration.google.connect',
  INTEGRATION_GOOGLE_DISCONNECT: 'integration.google.disconnect',
  GOOGLE_DRIVE_READ: 'google.drive.read',
  GOOGLE_DRIVE_WRITE: 'google.drive.write',
  GOOGLE_CALENDAR_READ: 'google.calendar.read',
  GOOGLE_CALENDAR_WRITE: 'google.calendar.write',
  GOOGLE_GMAIL_SEND: 'google.gmail.send',

  // Admin Administration
  ADMIN_USERS_MANAGE: 'admin.users.manage',
};

export const ROLE_PERMISSIONS = {
  employee: [
    PERMISSIONS.WORKFLOW_CREATE,
    PERMISSIONS.WORKFLOW_READ_SELF,
    PERMISSIONS.WORKFLOW_UPDATE_SELF,
    PERMISSIONS.TASK_READ_SELF,
    PERMISSIONS.TASK_COMPLETE,
    PERMISSIONS.APPROVAL_READ,
    PERMISSIONS.INTEGRATION_GOOGLE_CONNECT,
    PERMISSIONS.INTEGRATION_GOOGLE_DISCONNECT,
    PERMISSIONS.GOOGLE_DRIVE_READ,
    PERMISSIONS.GOOGLE_CALENDAR_READ,
    PERMISSIONS.GOOGLE_CALENDAR_WRITE,
    PERMISSIONS.GOOGLE_GMAIL_SEND,
  ],

  manager: [
    // Employee permissions +
    PERMISSIONS.WORKFLOW_CREATE,
    PERMISSIONS.WORKFLOW_READ_SELF,
    PERMISSIONS.WORKFLOW_READ_TEAM,
    PERMISSIONS.WORKFLOW_UPDATE_SELF,
    PERMISSIONS.TASK_READ_SELF,
    PERMISSIONS.TASK_READ_TEAM,
    PERMISSIONS.TASK_ASSIGN,
    PERMISSIONS.TASK_COMPLETE,
    PERMISSIONS.APPROVAL_READ,
    PERMISSIONS.APPROVAL_APPROVE,
    PERMISSIONS.APPROVAL_REJECT,
    PERMISSIONS.REPORT_READ,
    PERMISSIONS.MONITOR_READ,
    PERMISSIONS.INTEGRATION_GOOGLE_CONNECT,
    PERMISSIONS.INTEGRATION_GOOGLE_DISCONNECT,
    PERMISSIONS.GOOGLE_DRIVE_READ,
    PERMISSIONS.GOOGLE_CALENDAR_READ,
    PERMISSIONS.GOOGLE_CALENDAR_WRITE,
    PERMISSIONS.GOOGLE_GMAIL_SEND,
  ],

  finance: [
    PERMISSIONS.WORKFLOW_CREATE,
    PERMISSIONS.WORKFLOW_READ_SELF,
    PERMISSIONS.WORKFLOW_READ_DEPARTMENT,
    PERMISSIONS.TASK_READ_DEPARTMENT,
    PERMISSIONS.EXPENSE_READ,
    PERMISSIONS.EXPENSE_PROCESS,
    PERMISSIONS.APPROVAL_READ,
    PERMISSIONS.REPORT_READ,
    PERMISSIONS.REPORT_GENERATE,
    PERMISSIONS.INTEGRATION_GOOGLE_CONNECT,
    PERMISSIONS.INTEGRATION_GOOGLE_DISCONNECT,
  ],

  hr: [
    PERMISSIONS.WORKFLOW_CREATE,
    PERMISSIONS.WORKFLOW_READ_SELF,
    PERMISSIONS.WORKFLOW_READ_DEPARTMENT,
    PERMISSIONS.ONBOARDING_READ,
    PERMISSIONS.ONBOARDING_MANAGE,
    PERMISSIONS.TASK_READ_DEPARTMENT,
    PERMISSIONS.TASK_ASSIGN,
    PERMISSIONS.REPORT_READ,
    PERMISSIONS.REPORT_GENERATE,
    PERMISSIONS.INTEGRATION_GOOGLE_CONNECT,
    PERMISSIONS.INTEGRATION_GOOGLE_DISCONNECT,
  ],

  it_support: [
    PERMISSIONS.WORKFLOW_CREATE,
    PERMISSIONS.WORKFLOW_READ_SELF,
    PERMISSIONS.WORKFLOW_READ_DEPARTMENT,
    PERMISSIONS.HELPDESK_READ,
    PERMISSIONS.HELPDESK_MANAGE,
    PERMISSIONS.TASK_READ_DEPARTMENT,
    PERMISSIONS.TASK_ASSIGN,
    PERMISSIONS.TASK_COMPLETE,
    PERMISSIONS.MONITOR_READ,
    PERMISSIONS.INTEGRATION_GOOGLE_CONNECT,
    PERMISSIONS.INTEGRATION_GOOGLE_DISCONNECT,
  ],
  it: [
    PERMISSIONS.WORKFLOW_CREATE,
    PERMISSIONS.WORKFLOW_READ_SELF,
    PERMISSIONS.WORKFLOW_READ_DEPARTMENT,
    PERMISSIONS.HELPDESK_READ,
    PERMISSIONS.HELPDESK_MANAGE,
    PERMISSIONS.TASK_READ_DEPARTMENT,
    PERMISSIONS.TASK_ASSIGN,
    PERMISSIONS.TASK_COMPLETE,
    PERMISSIONS.MONITOR_READ,
    PERMISSIONS.INTEGRATION_GOOGLE_CONNECT,
    PERMISSIONS.INTEGRATION_GOOGLE_DISCONNECT,
  ],

  procurement: [
    PERMISSIONS.WORKFLOW_CREATE,
    PERMISSIONS.WORKFLOW_READ_SELF,
    PERMISSIONS.WORKFLOW_READ_DEPARTMENT,
    PERMISSIONS.TASK_READ_DEPARTMENT,
    PERMISSIONS.TASK_ASSIGN,
    PERMISSIONS.APPROVAL_READ,
    PERMISSIONS.INTEGRATION_GOOGLE_CONNECT,
    PERMISSIONS.INTEGRATION_GOOGLE_DISCONNECT,
  ],

  admin: Object.values(PERMISSIONS), // Admin has all permissions
};
